import type {
  Patient,
  Alert,
  TimelineEvent,
  Message,
  Notification,
  AISummary,
  AIRecommendation,
  DoctorProfile,
} from "./types"

export const patients: Patient[] = [
  {
    id: "1",
    name: "John Smith",
    age: 67,
    photo: "/avatars/patient-1.jpg",
    condition: "Diabetes Type 2",
    diagnosis: "Type 2 Diabetes Mellitus with hypertension",
    riskScore: 82,
    status: "red",
    lastActivity: "2 hours ago",
    lastUpdate: "2024-01-15T10:30:00",
    adherenceScore: 65,
  },
  {
    id: "2",
    name: "Maria Garcia",
    age: 54,
    photo: "/avatars/patient-2.jpg",
    condition: "Cardiovascular",
    diagnosis: "Chronic Heart Failure, NYHA Class II",
    riskScore: 71,
    status: "red",
    lastActivity: "4 hours ago",
    lastUpdate: "2024-01-15T08:15:00",
    adherenceScore: 72,
  },
  {
    id: "3",
    name: "Robert Johnson",
    age: 72,
    photo: "/avatars/patient-3.jpg",
    condition: "COPD",
    diagnosis: "Chronic Obstructive Pulmonary Disease, Stage III",
    riskScore: 58,
    status: "yellow",
    lastActivity: "1 day ago",
    lastUpdate: "2024-01-14T16:45:00",
    adherenceScore: 85,
  },
  {
    id: "4",
    name: "Emily Chen",
    age: 45,
    photo: "/avatars/patient-4.jpg",
    condition: "Hypertension",
    diagnosis: "Essential Hypertension, Stage 2",
    riskScore: 45,
    status: "yellow",
    lastActivity: "6 hours ago",
    lastUpdate: "2024-01-15T06:00:00",
    adherenceScore: 90,
  },
  {
    id: "5",
    name: "Michael Brown",
    age: 61,
    photo: "/avatars/patient-5.jpg",
    condition: "Diabetes Type 2",
    diagnosis: "Type 2 Diabetes with neuropathy",
    riskScore: 38,
    status: "green",
    lastActivity: "3 hours ago",
    lastUpdate: "2024-01-15T09:20:00",
    adherenceScore: 95,
  },
  {
    id: "6",
    name: "Sarah Wilson",
    age: 58,
    photo: "/avatars/patient-6.jpg",
    condition: "Cardiovascular",
    diagnosis: "Atrial Fibrillation, Stable",
    riskScore: 28,
    status: "green",
    lastActivity: "12 hours ago",
    lastUpdate: "2024-01-15T00:30:00",
    adherenceScore: 98,
  },
  {
    id: "7",
    name: "David Lee",
    age: 49,
    photo: "/avatars/patient-7.jpg",
    condition: "Hypertension",
    diagnosis: "Controlled Hypertension",
    riskScore: 22,
    status: "green",
    lastActivity: "1 day ago",
    lastUpdate: "2024-01-14T14:00:00",
    adherenceScore: 92,
  },
  {
    id: "8",
    name: "Jennifer Martinez",
    age: 63,
    photo: "/avatars/patient-8.jpg",
    condition: "COPD",
    diagnosis: "COPD with acute exacerbation history",
    riskScore: 67,
    status: "yellow",
    lastActivity: "5 hours ago",
    lastUpdate: "2024-01-15T07:30:00",
    adherenceScore: 78,
  },
]

export const alerts: Alert[] = [
  {
    id: "a1",
    patientId: "1",
    patientName: "John Smith",
    type: "vitals",
    severity: "high",
    headline: "Blood Pressure Spike Detected",
    cause: "BP reading significantly above threshold",
    metric: "BP: 180/110 mmHg",
    time: "10 minutes ago",
    status: "active",
  },
  {
    id: "a2",
    patientId: "2",
    patientName: "Maria Garcia",
    type: "behavior",
    severity: "high",
    headline: "Missed Medication - 3 Days",
    cause: "Patient has not logged medication intake",
    time: "1 hour ago",
    status: "active",
  },
  {
    id: "a3",
    patientId: "1",
    patientName: "John Smith",
    type: "ai",
    severity: "medium",
    headline: "AI: Deterioration Pattern Detected",
    cause: "Multiple indicators suggest worsening condition",
    time: "2 hours ago",
    status: "active",
  },
  {
    id: "a4",
    patientId: "3",
    patientName: "Robert Johnson",
    type: "vitals",
    severity: "medium",
    headline: "Oxygen Saturation Low",
    cause: "SpO2 dropped below 92%",
    metric: "SpO2: 90%",
    time: "4 hours ago",
    status: "active",
  },
  {
    id: "a5",
    patientId: "8",
    patientName: "Jennifer Martinez",
    type: "ai",
    severity: "low",
    headline: "AI: Activity Pattern Change",
    cause: "Reduced physical activity detected",
    time: "6 hours ago",
    status: "active",
  },
]

export const timelineEvents: TimelineEvent[] = [
  {
    id: "t1",
    patientId: "1",
    type: "device",
    date: "2024-01-15T10:30:00",
    headline: "Blood Pressure Reading",
    description: "BP: 180/110 mmHg - Above threshold",
    fullText: "Automated reading from home BP monitor. Systolic pressure significantly elevated. Patient reported feeling dizzy.",
  },
  {
    id: "t2",
    patientId: "1",
    type: "symptom",
    date: "2024-01-15T09:00:00",
    headline: "Patient Reported Headache",
    description: "Moderate headache since morning",
    fullText: "Patient reported via AI assistant: Experiencing moderate headache (6/10 pain scale) since waking up. No visual disturbances.",
  },
  {
    id: "t3",
    patientId: "1",
    type: "ai",
    date: "2024-01-15T08:00:00",
    headline: "AI Check-in Summary",
    description: "Morning wellness check completed",
    fullText: "Patient completed morning check-in. Mood: Fair. Sleep quality: Poor (4 hours). Energy level: Low. AI flagged potential correlation with medication timing.",
  },
  {
    id: "t4",
    patientId: "1",
    type: "note",
    date: "2024-01-14T14:30:00",
    headline: "Doctor Note: Medication Review",
    description: "Discussed medication adjustments",
    fullText: "Reviewed current medication regimen with patient. Discussed importance of consistent timing. Patient agreed to set daily reminders. Follow-up in 1 week.",
  },
  {
    id: "t5",
    patientId: "1",
    type: "visit",
    date: "2024-01-10T10:00:00",
    headline: "In-Person Visit",
    description: "Routine follow-up appointment",
    fullText: "Physical examination: Stable. Weight: 185 lbs (up 3 lbs). BP in clinic: 145/92. Discussed lifestyle modifications. Labs ordered.",
  },
]

export const messages: Message[] = [
  {
    id: "m1",
    patientId: "1",
    patientName: "John Smith",
    patientPhoto: "/avatars/patient-1.jpg",
    content: "Dr. Wilson, I took my BP reading this morning and it was quite high. Should I be concerned?",
    time: "10:35 AM",
    isFromDoctor: false,
  },
  {
    id: "m2",
    patientId: "1",
    patientName: "John Smith",
    patientPhoto: "/avatars/patient-1.jpg",
    content: "I see your reading, John. Please rest and avoid strenuous activity. I will review and get back to you shortly.",
    time: "10:42 AM",
    isFromDoctor: true,
  },
  {
    id: "m3",
    patientId: "2",
    patientName: "Maria Garcia",
    patientPhoto: "/avatars/patient-2.jpg",
    content: "Hello, I have been feeling more fatigued than usual lately.",
    time: "9:15 AM",
    isFromDoctor: false,
  },
  {
    id: "m4",
    patientId: "4",
    patientName: "Emily Chen",
    patientPhoto: "/avatars/patient-4.jpg",
    content: "Thank you for the prescription renewal, Doctor.",
    time: "Yesterday",
    isFromDoctor: false,
  },
]

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "alert",
    title: "High Priority Alert",
    description: "John Smith: Blood pressure spike detected",
    time: "10 min ago",
    read: false,
  },
  {
    id: "n2",
    type: "message",
    title: "New Message",
    description: "Maria Garcia sent you a message",
    time: "1 hour ago",
    read: false,
  },
  {
    id: "n3",
    type: "system",
    title: "Weekly Report Ready",
    description: "Your patient analytics report is ready",
    time: "2 hours ago",
    read: true,
  },
  {
    id: "n4",
    type: "alert",
    title: "Medium Priority Alert",
    description: "Robert Johnson: SpO2 below threshold",
    time: "4 hours ago",
    read: true,
  },
]

export const aiSummaries: Record<string, AISummary> = {
  "1": {
    patientId: "1",
    title: "Weekly Summary",
    insights: [
      "Blood pressure trending upward over past 7 days",
      "Medication adherence at 65% (below target)",
      "Sleep patterns irregular - averaging 5.2 hours",
      "Reported headaches 3 times this week",
      "Physical activity decreased by 40%",
    ],
    generatedAt: "2024-01-15T06:00:00",
  },
  "2": {
    patientId: "2",
    title: "Weekly Summary",
    insights: [
      "Heart rate variability within normal range",
      "Missed medication doses: 3 in past week",
      "Fatigue levels reported as increasing",
      "Weight stable at 142 lbs",
    ],
    generatedAt: "2024-01-15T06:00:00",
  },
}

export const aiRecommendations: AIRecommendation[] = [
  {
    id: "r1",
    patientId: "1",
    text: "Consider adjusting antihypertensive medication dosage",
    acknowledged: false,
  },
  {
    id: "r2",
    patientId: "1",
    text: "Check for potential medication interaction with OTC pain relievers",
    acknowledged: false,
  },
  {
    id: "r3",
    patientId: "2",
    text: "Schedule follow-up to discuss fatigue symptoms",
    acknowledged: false,
  },
]

export const doctorProfile: DoctorProfile = {
  id: "d1",
  name: "Dr. Sarah Wilson",
  specialization: "Internal Medicine",
  email: "sarah.wilson@clinic.com",
  phone: "+1 (555) 123-4567",
  photo: "/avatars/doctor.jpg",
}

export const dashboardStats = {
  totalPatients: 248,
  highRiskPatients: 12,
  alertsToday: 8,
  missedMedications: 15,
}
