import type {
  Patient,
  Alert,
  TimelineEvent,
  Message,
  Notification,
  AISummary,
  AIRecommendation,
  DoctorProfile,
  Provider,
  Region,
  Specialty,
} from "./types"

export const patients: Patient[] = [
  {
    id: "1",
    name: "John Smith",
    age: 67,
    photo: "/avatars/patient-1.jpg",
    condition: "Diabetes Type 2",
    diagnosis: "Type 2 Diabetes Mellitus with hypertension",
    riskScore: 82,
    status: "red",
    lastActivity: "2 hours ago",
    lastUpdate: "2024-01-15T10:30:00",
    adherenceScore: 65,
  },
  {
    id: "2",
    name: "Maria Garcia",
    age: 54,
    photo: "/avatars/patient-2.jpg",
    condition: "Cardiovascular",
    diagnosis: "Chronic Heart Failure, NYHA Class II",
    riskScore: 71,
    status: "red",
    lastActivity: "4 hours ago",
    lastUpdate: "2024-01-15T08:15:00",
    adherenceScore: 72,
  },
  {
    id: "3",
    name: "Robert Johnson",
    age: 72,
    photo: "/avatars/patient-3.jpg",
    condition: "COPD",
    diagnosis: "Chronic Obstructive Pulmonary Disease, Stage III",
    riskScore: 58,
    status: "yellow",
    lastActivity: "1 day ago",
    lastUpdate: "2024-01-14T16:45:00",
    adherenceScore: 85,
  },
  {
    id: "4",
    name: "Emily Chen",
    age: 45,
    photo: "/avatars/patient-4.jpg",
    condition: "Hypertension",
    diagnosis: "Essential Hypertension, Stage 2",
    riskScore: 45,
    status: "yellow",
    lastActivity: "6 hours ago",
    lastUpdate: "2024-01-15T06:00:00",
    adherenceScore: 90,
  },
  {
    id: "5",
    name: "Michael Brown",
    age: 61,
    photo: "/avatars/patient-5.jpg",
    condition: "Diabetes Type 2",
    diagnosis: "Type 2 Diabetes with neuropathy",
    riskScore: 38,
    status: "green",
    lastActivity: "3 hours ago",
    lastUpdate: "2024-01-15T09:20:00",
    adherenceScore: 95,
  },
  {
    id: "6",
    name: "Sarah Wilson",
    age: 58,
    photo: "/avatars/patient-6.jpg",
    condition: "Cardiovascular",
    diagnosis: "Atrial Fibrillation, Stable",
    riskScore: 28,
    status: "green",
    lastActivity: "12 hours ago",
    lastUpdate: "2024-01-15T00:30:00",
    adherenceScore: 98,
  },
  {
    id: "7",
    name: "David Lee",
    age: 49,
    photo: "/avatars/patient-7.jpg",
    condition: "Hypertension",
    diagnosis: "Controlled Hypertension",
    riskScore: 22,
    status: "green",
    lastActivity: "1 day ago",
    lastUpdate: "2024-01-14T14:00:00",
    adherenceScore: 92,
  },
  {
    id: "8",
    name: "Jennifer Martinez",
    age: 63,
    photo: "/avatars/patient-8.jpg",
    condition: "COPD",
    diagnosis: "COPD with acute exacerbation history",
    riskScore: 67,
    status: "yellow",
    lastActivity: "5 hours ago",
    lastUpdate: "2024-01-15T07:30:00",
    adherenceScore: 78,
  },
]

export const alerts: Alert[] = [
  {
    id: "a1",
    patientId: "1",
    patientName: "John Smith",
    type: "vitals",
    severity: "high",
    headline: "Blood Pressure Spike Detected",
    cause: "BP reading significantly above threshold",
    metric: "BP: 180/110 mmHg",
    time: "10 minutes ago",
    status: "active",
  },
  {
    id: "a2",
    patientId: "2",
    patientName: "Maria Garcia",
    type: "behavior",
    severity: "high",
    headline: "Missed Medication - 3 Days",
    cause: "Patient has not logged medication intake",
    time: "1 hour ago",
    status: "active",
  },
  {
    id: "a3",
    patientId: "1",
    patientName: "John Smith",
    type: "ai",
    severity: "medium",
    headline: "AI: Deterioration Pattern Detected",
    cause: "Multiple indicators suggest worsening condition",
    time: "2 hours ago",
    status: "active",
  },
  {
    id: "a4",
    patientId: "3",
    patientName: "Robert Johnson",
    type: "vitals",
    severity: "medium",
    headline: "Oxygen Saturation Low",
    cause: "SpO2 dropped below 92%",
    metric: "SpO2: 90%",
    time: "4 hours ago",
    status: "active",
  },
  {
    id: "a5",
    patientId: "8",
    patientName: "Jennifer Martinez",
    type: "ai",
    severity: "low",
    headline: "AI: Activity Pattern Change",
    cause: "Reduced physical activity detected",
    time: "6 hours ago",
    status: "active",
  },
]

export const timelineEvents: TimelineEvent[] = [
  {
    id: "t1",
    patientId: "1",
    type: "device",
    date: "2024-01-15T10:30:00",
    headline: "Blood Pressure Reading",
    description: "BP: 180/110 mmHg - Above threshold",
    fullText: "Automated reading from home BP monitor. Systolic pressure significantly elevated. Patient reported feeling dizzy.",
  },
  {
    id: "t2",
    patientId: "1",
    type: "symptom",
    date: "2024-01-15T09:00:00",
    headline: "Patient Reported Headache",
    description: "Moderate headache since morning",
    fullText: "Patient reported via AI assistant: Experiencing moderate headache (6/10 pain scale) since waking up. No visual disturbances.",
  },
  {
    id: "t3",
    patientId: "1",
    type: "ai",
    date: "2024-01-15T08:00:00",
    headline: "AI Check-in Summary",
    description: "Morning wellness check completed",
    fullText: "Patient completed morning check-in. Mood: Fair. Sleep quality: Poor (4 hours). Energy level: Low. AI flagged potential correlation with medication timing.",
  },
  {
    id: "t4",
    patientId: "1",
    type: "note",
    date: "2024-01-14T14:30:00",
    headline: "Doctor Note: Medication Review",
    description: "Discussed medication adjustments",
    fullText: "Reviewed current medication regimen with patient. Discussed importance of consistent timing. Patient agreed to set daily reminders. Follow-up in 1 week.",
  },
  {
    id: "t5",
    patientId: "1",
    type: "visit",
    date: "2024-01-10T10:00:00",
    headline: "In-Person Visit",
    description: "Routine follow-up appointment",
    fullText: "Physical examination: Stable. Weight: 185 lbs (up 3 lbs). BP in clinic: 145/92. Discussed lifestyle modifications. Labs ordered.",
  },
]

export const messages: Message[] = [
  {
    id: "m1",
    patientId: "1",
    patientName: "John Smith",
    patientPhoto: "/avatars/patient-1.jpg",
    content: "Dr. Wilson, I took my BP reading this morning and it was quite high. Should I be concerned?",
    time: "10:35 AM",
    isFromDoctor: false,
  },
  {
    id: "m2",
    patientId: "1",
    patientName: "John Smith",
    patientPhoto: "/avatars/patient-1.jpg",
    content: "I see your reading, John. Please rest and avoid strenuous activity. I will review and get back to you shortly.",
    time: "10:42 AM",
    isFromDoctor: true,
  },
  {
    id: "m3",
    patientId: "2",
    patientName: "Maria Garcia",
    patientPhoto: "/avatars/patient-2.jpg",
    content: "Hello, I have been feeling more fatigued than usual lately.",
    time: "9:15 AM",
    isFromDoctor: false,
  },
  {
    id: "m4",
    patientId: "4",
    patientName: "Emily Chen",
    patientPhoto: "/avatars/patient-4.jpg",
    content: "Thank you for the prescription renewal, Doctor.",
    time: "Yesterday",
    isFromDoctor: false,
  },
]

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "alert",
    title: "High Priority Alert",
    description: "John Smith: Blood pressure spike detected",
    time: "10 min ago",
    read: false,
  },
  {
    id: "n2",
    type: "message",
    title: "New Message",
    description: "Maria Garcia sent you a message",
    time: "1 hour ago",
    read: false,
  },
  {
    id: "n3",
    type: "system",
    title: "Weekly Report Ready",
    description: "Your patient analytics report is ready",
    time: "2 hours ago",
    read: true,
  },
  {
    id: "n4",
    type: "alert",
    title: "Medium Priority Alert",
    description: "Robert Johnson: SpO2 below threshold",
    time: "4 hours ago",
    read: true,
  },
]

export const aiSummaries: Record<string, AISummary> = {
  "1": {
    patientId: "1",
    title: "Weekly Summary",
    insights: [
      "Blood pressure trending upward over past 7 days",
      "Medication adherence at 65% (below target)",
      "Sleep patterns irregular - averaging 5.2 hours",
      "Reported headaches 3 times this week",
      "Physical activity decreased by 40%",
    ],
    generatedAt: "2024-01-15T06:00:00",
  },
  "2": {
    patientId: "2",
    title: "Weekly Summary",
    insights: [
      "Heart rate variability within normal range",
      "Missed medication doses: 3 in past week",
      "Fatigue levels reported as increasing",
      "Weight stable at 142 lbs",
    ],
    generatedAt: "2024-01-15T06:00:00",
  },
}

export const aiRecommendations: AIRecommendation[] = [
  {
    id: "r1",
    patientId: "1",
    text: "Consider adjusting antihypertensive medication dosage",
    acknowledged: false,
  },
  {
    id: "r2",
    patientId: "1",
    text: "Check for potential medication interaction with OTC pain relievers",
    acknowledged: false,
  },
  {
    id: "r3",
    patientId: "2",
    text: "Schedule follow-up to discuss fatigue symptoms",
    acknowledged: false,
  },
]

export const doctorProfile: DoctorProfile = {
  id: "d1",
  name: "Dr. Sarah Wilson",
  specialization: "Internal Medicine",
  email: "sarah.wilson@clinic.com",
  phone: "+1 (555) 123-4567",
  photo: "/avatars/doctor.jpg",
}

export const dashboardStats = {
  totalPatients: 248,
  highRiskPatients: 12,
  alertsToday: 8,
  missedMedications: 15,
}

// ─── Provider Search ───────────────────────────────────────────────────────────

export const providers: Provider[] = [
  {
    npi: "1234567890",
    firstName: "James",
    lastName: "Hartwell",
    organization: "Buffalo General Medical Center",
    specialty: "Cardiology",
    region: "Western New York",
    billingCodes: [
      { code: "99213", description: "Office visit, low complexity", usageCount: 820 },
      { code: "93000", description: "Electrocardiogram", usageCount: 640 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 310 },
    ],
  },
  {
    npi: "2345678901",
    firstName: "Patricia",
    lastName: "Nguyen",
    organization: "Long Island Jewish Medical Center",
    specialty: "Internal Medicine",
    region: "Long Island",
    billingCodes: [
      { code: "99213", description: "Office visit, low complexity", usageCount: 1240 },
      { code: "99232", description: "Subsequent hospital care", usageCount: 980 },
      { code: "99215", description: "Office visit, high complexity", usageCount: 560 },
    ],
  },
  {
    npi: "3456789012",
    firstName: "Robert",
    lastName: "Chen",
    organization: "NYU Langone Health",
    specialty: "Orthopedics",
    region: "New York City",
    billingCodes: [
      { code: "27447", description: "Total knee arthroplasty", usageCount: 310 },
      { code: "29881", description: "Knee arthroscopy", usageCount: 275 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 490 },
    ],
  },
  {
    npi: "4567890123",
    firstName: "Linda",
    lastName: "Morrison",
    organization: "Hudson Valley Neurology Associates",
    specialty: "Neurology",
    region: "Hudson Valley",
    billingCodes: [
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 760 },
      { code: "95816", description: "EEG, awake and drowsy", usageCount: 430 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 390 },
    ],
  },
  {
    npi: "5678901234",
    firstName: "David",
    lastName: "Okafor",
    organization: "Albany Medical Center",
    specialty: "Oncology",
    region: "Capital Region",
    billingCodes: [
      { code: "99215", description: "Office visit, high complexity", usageCount: 890 },
      { code: "96413", description: "Chemotherapy administration", usageCount: 1450 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 620 },
    ],
  },
  {
    npi: "6789012345",
    firstName: "Susan",
    lastName: "Kowalski",
    organization: "Upstate Pediatric Associates",
    specialty: "Pediatrics",
    region: "Central New York",
    billingCodes: [
      { code: "99213", description: "Office visit, low complexity", usageCount: 1100 },
      { code: "99391", description: "Preventive care, infant", usageCount: 870 },
      { code: "99392", description: "Preventive care, early childhood", usageCount: 640 },
    ],
  },
  {
    npi: "7890123456",
    firstName: "Michael",
    lastName: "Torres",
    organization: "North Country Behavioral Health",
    specialty: "Psychiatry",
    region: "North Country",
    billingCodes: [
      { code: "90837", description: "Psychotherapy, 60 min", usageCount: 2100 },
      { code: "90834", description: "Psychotherapy, 45 min", usageCount: 1850 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 430 },
    ],
  },
  {
    npi: "8901234567",
    firstName: "Angela",
    lastName: "Reyes",
    organization: "Southern Tier Radiology Group",
    specialty: "Radiology",
    region: "Southern Tier",
    billingCodes: [
      { code: "71046", description: "Chest X-ray, 2 views", usageCount: 3200 },
      { code: "74177", description: "CT abdomen and pelvis", usageCount: 2800 },
      { code: "70553", description: "MRI brain with contrast", usageCount: 1750 },
    ],
  },
  {
    npi: "9012345678",
    firstName: "Thomas",
    lastName: "Blackwell",
    organization: "Finger Lakes Surgical Associates",
    specialty: "General Surgery",
    region: "Finger Lakes",
    billingCodes: [
      { code: "43239", description: "Esophagogastroduodenoscopy", usageCount: 480 },
      { code: "44950", description: "Appendectomy", usageCount: 145 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 310 },
    ],
  },
  {
    npi: "0123456789",
    firstName: "Karen",
    lastName: "Patel",
    organization: "Mohawk Valley Family Health Center",
    specialty: "Family Medicine",
    region: "Mohawk Valley",
    billingCodes: [
      { code: "99213", description: "Office visit, low complexity", usageCount: 1680 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 920 },
      { code: "99395", description: "Preventive care, 18–39 years", usageCount: 540 },
    ],
  },
  {
    npi: "1357924680",
    firstName: "Brian",
    lastName: "Schwartz",
    organization: "Brooklyn Endocrinology Center",
    specialty: "Endocrinology",
    region: "New York City",
    billingCodes: [
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 1920 },
      { code: "83036", description: "Hemoglobin A1c", usageCount: 3400 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 1100 },
    ],
  },
  {
    npi: "2468013579",
    firstName: "Donna",
    lastName: "Fitzgerald",
    organization: "Nassau County Nephrology Group",
    specialty: "Nephrology",
    region: "Long Island",
    billingCodes: [
      { code: "90960", description: "End-stage renal disease, per month", usageCount: 4100 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 870 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 640 },
    ],
  },
  {
    npi: "1122334455",
    firstName: "Gregory",
    lastName: "Walsh",
    organization: "Erie County Pulmonary Medicine",
    specialty: "Pulmonology",
    region: "Western New York",
    billingCodes: [
      { code: "94010", description: "Spirometry", usageCount: 1560 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 980 },
      { code: "94640", description: "Inhalation treatment", usageCount: 2200 },
    ],
  },
  {
    npi: "5544332211",
    firstName: "Olivia",
    lastName: "Marchetti",
    organization: "Capital Region Gastroenterology",
    specialty: "Gastroenterology",
    region: "Capital Region",
    billingCodes: [
      { code: "45378", description: "Colonoscopy, diagnostic", usageCount: 2650 },
      { code: "43239", description: "Esophagogastroduodenoscopy", usageCount: 1980 },
      { code: "99213", description: "Office visit, low complexity", usageCount: 720 },
    ],
  },
  {
    npi: "9988776655",
    firstName: "Kevin",
    lastName: "Drummond",
    organization: "Plattsburgh Internal Medicine Associates",
    specialty: "Internal Medicine",
    region: "North Country",
    billingCodes: [
      { code: "99213", description: "Office visit, low complexity", usageCount: 530 },
      { code: "99214", description: "Office visit, moderate complexity", usageCount: 310 },
      { code: "99215", description: "Office visit, high complexity", usageCount: 180 },
    ],
  },
]

export const providerRegions: string[] = [
  "Western New York",
  "Long Island",
  "New York City",
  "Hudson Valley",
  "Capital Region",
  "Central New York",
  "North Country",
  "Southern Tier",
  "Finger Lakes",
  "Mohawk Valley",
]

export const providerSpecialties: string[] = [
  "Cardiology",
  "Internal Medicine",
  "Orthopedics",
  "Neurology",
  "Oncology",
  "Pediatrics",
  "Psychiatry",
  "Radiology",
  "General Surgery",
  "Family Medicine",
  "Endocrinology",
  "Nephrology",
  "Pulmonology",
  "Gastroenterology",
]
